version: '3'
services:
  flask-app:
    image: gersenx3/grade-submission-portal:1.0.0
    container_name: flask-app
    ports:
      - "5001:5001"
    environment:
      - GRADE_SERVICE_HOST=node-server
    depends_on:
      - node-server

  node-server:
    image: gersenx3/grade-submission-api:1.0.0
    container_name: node-server
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=mongo-db
      - DB_PORT=27017
      - DB_NAME=grade_db
    depends_on:
      - mongo
  
  mongo:
    image: mongo:latest
    container_name: mongo-db
    environment:
      - MONGO_INITDB_DATABASE=grade_db
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
volumes:
  mongo-data:
